apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-config
  namespace: shop
  labels:
    app.kubernetes.io/part-of: shop
data:
  REDIS_HEADLESS_HOST: redis.shop-cache.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_TTL_SECONDS: "60"
